"""A0 - dataset analysis (plan §7 Phase A). $0. Writes results/a0/dataset_report.md (+ 2 plots).

Reads the dataset directly (analysis side; allowed to see labels).
"""
from __future__ import annotations

import json
import re
from collections import Counter, defaultdict

from common import ROOT, out_dir

DS = ROOT / "data" / "opspilot_itsm_data"
SETS = ["dev_runs", "heldout_runs", "premature_dev", "premature_heldout", "correct_dev", "correct_heldout", "guardrail"]
DECISIONS = ["VERIFIED", "INCOMPLETE", "ESCALATE"]

# Validated categorical palette (dataviz skill references/palette.md), light-surface slots 1-3,
# in the order that clears every CVD/normal-vision adjacent-pair gate. not_declared is not a
# decision outcome (no attempt was released), so it stays baseline gray, not a fourth hue.
COLOR = {"VERIFIED": "#2a78d6", "INCOMPLETE": "#eb6834", "ESCALATE": "#1baf7a", "not_declared": "#c3c2b7"}
SURFACE, INK, INK_2, MUTED, GRID = "#fcfcfb", "#0b0b0b", "#52514e", "#898781", "#e1e0d9"


def jl(p):
    return [json.loads(l) for l in p.read_text().splitlines() if l.strip()]


def _style(ax):
    ax.set_facecolor(SURFACE)
    ax.tick_params(colors=INK_2, labelsize=9)
    ax.grid(axis="x", color=GRID, linewidth=0.8, zorder=0)
    ax.set_axisbelow(True)
    for spine in ax.spines.values():
        spine.set_visible(False)


def plot_decision_distribution(set_stats, path):
    import matplotlib
    matplotlib.use("Agg")
    import numpy as np
    import matplotlib.pyplot as plt

    sets = [s for s, _ in set_stats]
    fig, ax = plt.subplots(figsize=(8, 4.5), facecolor=SURFACE)
    left = np.zeros(len(sets))
    for cat in DECISIONS + ["not_declared"]:
        vals = np.array([d.get(cat, 0) for _, d in set_stats], dtype=float)
        ax.barh(sets, vals, left=left, color=COLOR[cat], label=cat, height=0.6)
        left += vals
    _style(ax)
    ax.invert_yaxis()
    ax.set_xlabel("cases", color=INK_2)
    ax.set_title("Decision distribution by set (declared + not-declared)", color=INK, loc="left", fontsize=11)
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.14), ncol=4, frameon=False, labelcolor=INK_2, fontsize=9)
    fig.tight_layout()
    fig.savefig(path, dpi=150, facecolor=SURFACE)
    plt.close(fig)


def plot_negatives_by_family(neg, path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    counts = Counter(l["family"] for l in neg)
    order = sorted(counts, key=lambda f: -counts[f])
    vals = [counts[f] for f in order]
    fig, ax = plt.subplots(figsize=(7.5, 4), facecolor=SURFACE)
    bars = ax.barh(order, vals, color=COLOR["VERIFIED"], height=0.6)  # single series: sequential blue
    _style(ax)
    ax.invert_yaxis()
    for b, v in zip(bars, vals):
        ax.text(b.get_width() + max(vals) * 0.02, b.get_y() + b.get_height() / 2, str(v),
                va="center", color=INK_2, fontsize=9)
    ax.set_xlabel("negative (false-closure) cases", color=INK_2)
    ax.set_title("Negative cases by family", color=INK, loc="left", fontsize=11)
    fig.tight_layout()
    fig.savefig(path, dpi=150, facecolor=SURFACE)
    plt.close(fig)


def main():
    lines = ["# A0 - Dataset report (generated by analysis/eda.py)\n"]
    lines.append("| set | cases | VERIFIED | INCOMPLETE | ESCALATE | not declared | baseline FCR |\n|---|---:|---:|---:|---:|---:|---:|")
    allL, set_stats = {}, []
    for s in SETS:
        L = jl(DS / "hidden/labels" / f"{s}.jsonl")
        allL.update({l["case_id"]: l for l in L})
        dec = Counter(l["expected_decision"] for l in L if l["resolver_declared_resolved"])
        nd = sum(not l["resolver_declared_resolved"] for l in L)
        fcr = sum(l["resolver_declared_resolved"] and not l["verifier_pass"] for l in L) / len(L)
        set_stats.append((s, {**dec, "not_declared": nd}))
        lines.append(f"| {s} | {len(L)} | {dec['VERIFIED']} | {dec['INCOMPLETE']} | {dec['ESCALATE']} | {nd} | {100*fcr:.1f}% |")
    p_dist = out_dir("a0") / "decision_distribution.png"
    plot_decision_distribution(set_stats, p_dist)
    lines.append(f"\n![Decision distribution by set]({p_dist.name})\n")
    neg = [l for l in allL.values() if l["resolver_declared_resolved"] and not l["verifier_pass"]]
    lines.append(f"\n**Negative (false-closure) cases:** {len(neg)}\n")
    for key in ["family", "summary_honesty"]:
        c = Counter(str(l.get(key)) for l in neg)
        lines.append(f"\nNegatives by {key}: " + ", ".join(f"{k} {v}" for k, v in c.most_common()))
    p_neg = out_dir("a0") / "negatives_by_family.png"
    plot_negatives_by_family(neg, p_neg)
    lines.append(f"\n\n![Negative cases by family]({p_neg.name})\n")
    var = Counter(l["variant"].split(":")[0] + ":" + (l["variant"].split(":")[1] if ":" in l["variant"] else "")
                  for l in neg)
    lines.append("\nNegatives by variant: " + ", ".join(f"`{k}` {v}" for k, v in var.most_common(15)))
    cov = Counter(c for l in neg for c in l["required_failed"] + l["forbidden_triggered"] + l["precondition_failed"])
    lines.append("\n## Conditions per runbook and negative coverage\n\n| runbook | P | R | F | conditions never failing in any negative |\n|---|---:|---:|---:|---|")
    for rb in sorted((DS / "runbooks").glob("*.md")):
        ids = re.findall(r"^- ([A-Z]+-[PRF]\d+):", rb.read_text(), re.M)
        kinds = Counter(i.split("-")[1][0] for i in ids)
        never = [i for i in ids if cov[i] == 0]
        lines.append(f"| {rb.stem} | {kinds['P']} | {kinds['R']} | {kinds['F']} | {', '.join(never) or '-'} |")
    lines.append("\n## Guardrail catalogue\n\n| case | category | expected |\n|---|---|---|")
    for l in jl(DS / "hidden/labels/guardrail.jsonl"):
        lines.append(f"| {l['case_id']} | {l['guardrail_category']} | {l['expected_decision']} |")
    ex = next(c for c in jl(DS / "public/cases/premature_dev.jsonl"))
    lines.append("\n## Example case (public view) -> label\n\n```json\n" + json.dumps(
        {k: ex[k] for k in ("case_id", "runbook_id", "ticket", "proposed_closure")}, indent=1)
        + "\n```\nLabel: `" + json.dumps({k: allL[ex['case_id']][k] for k in
                                         ("expected_decision", "required_failed", "variant")}) + "`")
    lines.append("\n## Cost forecast (planning value, replace after A2)\n\n"
                 "Tier-1 case-runs ~ 360 agent-equivalents x $0.006 ~ $2.15 (plan §9).")
    p = out_dir("a0") / "dataset_report.md"
    p.write_text("\n".join(lines) + "\n")
    print("\n".join(lines[:12]))
    print(f"\n-> {p}")
    print(f"-> {p_dist}")
    print(f"-> {p_neg}")


if __name__ == "__main__":
    main()
